name: AIOI-CI-Frontend
on:
  push:
    branches:
      - master

jobs:
 deploy-frontend:
    name: Deploy Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print
        run: echo ${{ github.event.number }}



