name: AIOI-CI-Frontend
on:
  push:
    branches:
      - master

jobs:
 deploy-frontend:
    name: Deploy Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          FULL_NAME_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Change something
        run: |
          echo $FULL_NAME_REPO 



